apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    aadpodidbinding: my-pod-identity
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=3d3473aa-c602-4c19-88f0-a5b1e2987cd7
      - --clientid=668ac157-23c2-4953-976e-5e1c38d5230b
      - --resourcegroup=myIdentityResourceGroup
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux