apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sre
  name: sre-user-full-access
rules:
- apiGroups: ["", "extensions", "apps"] 
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"] 
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]





  