apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                         
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: leonsakv201            
    objects: |
      array:
        - |
          objectName: ingresscert
          objectType: secret
    tenantId: 839d9082-0162-437c-8d79-fbcddce362b6            