apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
      - name: istio-ingressgateway-argocd
        namespace: argocd
        enabled: true
        label:
          istio: istio-ingressgateway-argocd

